//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApplication_Tonsberg.wcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfService.itWebService")]
    public interface itWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeProfile", ReplyAction="http://tempuri.org/itWebService/Get_TraineeProfileResponse")]
        string Get_TraineeProfile(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeProfile", ReplyAction="http://tempuri.org/itWebService/Get_TraineeProfileResponse")]
        System.Threading.Tasks.Task<string> Get_TraineeProfileAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeList", ReplyAction="http://tempuri.org/itWebService/Get_TraineeListResponse")]
        string Get_TraineeList(int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeList", ReplyAction="http://tempuri.org/itWebService/Get_TraineeListResponse")]
        System.Threading.Tasks.Task<string> Get_TraineeListAsync(int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeRecord", ReplyAction="http://tempuri.org/itWebService/Get_TraineeRecordResponse")]
        string Get_TraineeRecord(string TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeRecord", ReplyAction="http://tempuri.org/itWebService/Get_TraineeRecordResponse")]
        System.Threading.Tasks.Task<string> Get_TraineeRecordAsync(string TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_AvailableCourses", ReplyAction="http://tempuri.org/itWebService/Get_AvailableCoursesResponse")]
        string Get_AvailableCourses(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_AvailableCourses", ReplyAction="http://tempuri.org/itWebService/Get_AvailableCoursesResponse")]
        System.Threading.Tasks.Task<string> Get_AvailableCoursesAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_EnrolledTrainee", ReplyAction="http://tempuri.org/itWebService/Get_EnrolledTraineeResponse")]
        string Get_EnrolledTrainee(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_EnrolledTrainee", ReplyAction="http://tempuri.org/itWebService/Get_EnrolledTraineeResponse")]
        System.Threading.Tasks.Task<string> Get_EnrolledTraineeAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TrainingCourses", ReplyAction="http://tempuri.org/itWebService/Get_TrainingCoursesResponse")]
        string Get_TrainingCourses(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TrainingCourses", ReplyAction="http://tempuri.org/itWebService/Get_TrainingCoursesResponse")]
        System.Threading.Tasks.Task<string> Get_TrainingCoursesAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_AccountsReceivableHistory", ReplyAction="http://tempuri.org/itWebService/Get_AccountsReceivableHistoryResponse")]
        string Get_AccountsReceivableHistory(int _CourseID, string _TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_AccountsReceivableHistory", ReplyAction="http://tempuri.org/itWebService/Get_AccountsReceivableHistoryResponse")]
        System.Threading.Tasks.Task<string> Get_AccountsReceivableHistoryAsync(int _CourseID, string _TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TotalAmountPaid", ReplyAction="http://tempuri.org/itWebService/Get_TotalAmountPaidResponse")]
        string Get_TotalAmountPaid(int _CourseID, string _TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TotalAmountPaid", ReplyAction="http://tempuri.org/itWebService/Get_TotalAmountPaidResponse")]
        System.Threading.Tasks.Task<string> Get_TotalAmountPaidAsync(int _CourseID, string _TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeAccountsReceivable", ReplyAction="http://tempuri.org/itWebService/Get_TraineeAccountsReceivableResponse")]
        string Get_TraineeAccountsReceivable(string TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TraineeAccountsReceivable", ReplyAction="http://tempuri.org/itWebService/Get_TraineeAccountsReceivableResponse")]
        System.Threading.Tasks.Task<string> Get_TraineeAccountsReceivableAsync(string TraineeID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/GetUserPass", ReplyAction="http://tempuri.org/itWebService/GetUserPassResponse")]
        string GetUserPass(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/GetUserPass", ReplyAction="http://tempuri.org/itWebService/GetUserPassResponse")]
        System.Threading.Tasks.Task<string> GetUserPassAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserAccessRights", ReplyAction="http://tempuri.org/itWebService/Get_UserAccessRightsResponse")]
        string Get_UserAccessRights(int GroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserAccessRights", ReplyAction="http://tempuri.org/itWebService/Get_UserAccessRightsResponse")]
        System.Threading.Tasks.Task<string> Get_UserAccessRightsAsync(int GroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserAccount", ReplyAction="http://tempuri.org/itWebService/Get_UserAccountResponse")]
        string Get_UserAccount(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserAccount", ReplyAction="http://tempuri.org/itWebService/Get_UserAccountResponse")]
        System.Threading.Tasks.Task<string> Get_UserAccountAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserGroups", ReplyAction="http://tempuri.org/itWebService/Get_UserGroupsResponse")]
        string Get_UserGroups(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_UserGroups", ReplyAction="http://tempuri.org/itWebService/Get_UserGroupsResponse")]
        System.Threading.Tasks.Task<string> Get_UserGroupsAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_GroupRights", ReplyAction="http://tempuri.org/itWebService/Get_GroupRightsResponse")]
        string Get_GroupRights(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_GroupRights", ReplyAction="http://tempuri.org/itWebService/Get_GroupRightsResponse")]
        System.Threading.Tasks.Task<string> Get_GroupRightsAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Gender", ReplyAction="http://tempuri.org/itWebService/Get_GenderResponse")]
        string Get_Gender(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Gender", ReplyAction="http://tempuri.org/itWebService/Get_GenderResponse")]
        System.Threading.Tasks.Task<string> Get_GenderAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_CivilStatus", ReplyAction="http://tempuri.org/itWebService/Get_CivilStatusResponse")]
        string Get_CivilStatus(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_CivilStatus", ReplyAction="http://tempuri.org/itWebService/Get_CivilStatusResponse")]
        System.Threading.Tasks.Task<string> Get_CivilStatusAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_SystemModules", ReplyAction="http://tempuri.org/itWebService/Get_SystemModulesResponse")]
        string Get_SystemModules(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_SystemModules", ReplyAction="http://tempuri.org/itWebService/Get_SystemModulesResponse")]
        System.Threading.Tasks.Task<string> Get_SystemModulesAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Office", ReplyAction="http://tempuri.org/itWebService/Get_OfficeResponse")]
        string Get_Office(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Office", ReplyAction="http://tempuri.org/itWebService/Get_OfficeResponse")]
        System.Threading.Tasks.Task<string> Get_OfficeAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Department", ReplyAction="http://tempuri.org/itWebService/Get_DepartmentResponse")]
        string Get_Department(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_Department", ReplyAction="http://tempuri.org/itWebService/Get_DepartmentResponse")]
        System.Threading.Tasks.Task<string> Get_DepartmentAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_AccountsReceivable_All", ReplyAction="http://tempuri.org/itWebService/Report_AccountsReceivable_AllResponse")]
        string Report_AccountsReceivable_All(string _DateFrom, string _DateTo, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_AccountsReceivable_All", ReplyAction="http://tempuri.org/itWebService/Report_AccountsReceivable_AllResponse")]
        System.Threading.Tasks.Task<string> Report_AccountsReceivable_AllAsync(string _DateFrom, string _DateTo, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_AccountsReceivable_Course", ReplyAction="http://tempuri.org/itWebService/Report_AccountsReceivable_CourseResponse")]
        string Report_AccountsReceivable_Course(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_AccountsReceivable_Course", ReplyAction="http://tempuri.org/itWebService/Report_AccountsReceivable_CourseResponse")]
        System.Threading.Tasks.Task<string> Report_AccountsReceivable_CourseAsync(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_Sales_All", ReplyAction="http://tempuri.org/itWebService/Report_Sales_AllResponse")]
        string Report_Sales_All(string _DateFrom, string _DateTo, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_Sales_All", ReplyAction="http://tempuri.org/itWebService/Report_Sales_AllResponse")]
        System.Threading.Tasks.Task<string> Report_Sales_AllAsync(string _DateFrom, string _DateTo, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_Sales_Course", ReplyAction="http://tempuri.org/itWebService/Report_Sales_CourseResponse")]
        string Report_Sales_Course(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Report_Sales_Course", ReplyAction="http://tempuri.org/itWebService/Report_Sales_CourseResponse")]
        System.Threading.Tasks.Task<string> Report_Sales_CourseAsync(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TraineeProfile", ReplyAction="http://tempuri.org/itWebService/Save_TraineeProfileResponse")]
        void Save_TraineeProfile(
                    string TraineeID, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    int GenderID, 
                    int CivilStatusID, 
                    string ContactNo, 
                    string DateOfBirth, 
                    int Age, 
                    string PlaceOfBirth, 
                    bool Active, 
                    string PositionRank, 
                    int YearsOfSeaExperience, 
                    string MarinaLicense, 
                    string PRCLicense, 
                    string SIRBNo, 
                    string PassportNo, 
                    string SRCNo, 
                    string Others, 
                    string EnrollmentDate, 
                    int _UserID, 
                    string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TraineeProfile", ReplyAction="http://tempuri.org/itWebService/Save_TraineeProfileResponse")]
        System.Threading.Tasks.Task Save_TraineeProfileAsync(
                    string TraineeID, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    int GenderID, 
                    int CivilStatusID, 
                    string ContactNo, 
                    string DateOfBirth, 
                    int Age, 
                    string PlaceOfBirth, 
                    bool Active, 
                    string PositionRank, 
                    int YearsOfSeaExperience, 
                    string MarinaLicense, 
                    string PRCLicense, 
                    string SIRBNo, 
                    string PassportNo, 
                    string SRCNo, 
                    string Others, 
                    string EnrollmentDate, 
                    int _UserID, 
                    string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TraineeRegistration", ReplyAction="http://tempuri.org/itWebService/Save_TraineeRegistrationResponse")]
        void Save_TraineeRegistration(int RegistrationID, string DateRegistered, string TraineeID, int CourseID, string CourseCode, bool DropTrainee, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TraineeRegistration", ReplyAction="http://tempuri.org/itWebService/Save_TraineeRegistrationResponse")]
        System.Threading.Tasks.Task Save_TraineeRegistrationAsync(int RegistrationID, string DateRegistered, string TraineeID, int CourseID, string CourseCode, bool DropTrainee, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_DropTrainee", ReplyAction="http://tempuri.org/itWebService/Save_DropTraineeResponse")]
        void Save_DropTrainee(string TraineeID, int CourseID, int RegistrationID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_DropTrainee", ReplyAction="http://tempuri.org/itWebService/Save_DropTraineeResponse")]
        System.Threading.Tasks.Task Save_DropTraineeAsync(string TraineeID, int CourseID, int RegistrationID, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TrainingCourses", ReplyAction="http://tempuri.org/itWebService/Save_TrainingCoursesResponse")]
        void Save_TrainingCourses(int CourseID, string CourseCode, string CourseName, string TrainorName, int NoOfTrainees, int TrainingDuration, string TrainingStartDate, bool Active, decimal TrainingFee, string AssessorName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TrainingCourses", ReplyAction="http://tempuri.org/itWebService/Save_TrainingCoursesResponse")]
        System.Threading.Tasks.Task Save_TrainingCoursesAsync(int CourseID, string CourseCode, string CourseName, string TrainorName, int NoOfTrainees, int TrainingDuration, string TrainingStartDate, bool Active, decimal TrainingFee, string AssessorName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Payments", ReplyAction="http://tempuri.org/itWebService/Save_PaymentsResponse")]
        void Save_Payments(int RegistrationID, decimal AmountPaid, string PaymentDetails, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Payments", ReplyAction="http://tempuri.org/itWebService/Save_PaymentsResponse")]
        System.Threading.Tasks.Task Save_PaymentsAsync(int RegistrationID, decimal AmountPaid, string PaymentDetails, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserAccounts", ReplyAction="http://tempuri.org/itWebService/Save_UserAccountsResponse")]
        void Save_UserAccounts(int UserID, string UserName, string Password, string FirstName, string LastName, int GroupID, string EmailAddress, string Office, int DepartmentID, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserAccounts", ReplyAction="http://tempuri.org/itWebService/Save_UserAccountsResponse")]
        System.Threading.Tasks.Task Save_UserAccountsAsync(int UserID, string UserName, string Password, string FirstName, string LastName, int GroupID, string EmailAddress, string Office, int DepartmentID, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserGroups", ReplyAction="http://tempuri.org/itWebService/Save_UserGroupsResponse")]
        void Save_UserGroups(int ID, string GroupName, string Description, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserGroups", ReplyAction="http://tempuri.org/itWebService/Save_UserGroupsResponse")]
        System.Threading.Tasks.Task Save_UserGroupsAsync(int ID, string GroupName, string Description, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_GroupRights", ReplyAction="http://tempuri.org/itWebService/Save_GroupRightsResponse")]
        void Save_GroupRights(int GroupRightID, int GroupID, int ModuleID, bool CanView, bool CanEdit, bool CanDelete, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_GroupRights", ReplyAction="http://tempuri.org/itWebService/Save_GroupRightsResponse")]
        System.Threading.Tasks.Task Save_GroupRightsAsync(int GroupRightID, int GroupID, int ModuleID, bool CanView, bool CanEdit, bool CanDelete, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserProfile", ReplyAction="http://tempuri.org/itWebService/Save_UserProfileResponse")]
        void Save_UserProfile(int UserID, string Password, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_UserProfile", ReplyAction="http://tempuri.org/itWebService/Save_UserProfileResponse")]
        System.Threading.Tasks.Task Save_UserProfileAsync(int UserID, string Password, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Gender", ReplyAction="http://tempuri.org/itWebService/Save_GenderResponse")]
        void Save_Gender(int GenderID, string GenderName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Gender", ReplyAction="http://tempuri.org/itWebService/Save_GenderResponse")]
        System.Threading.Tasks.Task Save_GenderAsync(int GenderID, string GenderName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_CivilStatus", ReplyAction="http://tempuri.org/itWebService/Save_CivilStatusResponse")]
        void Save_CivilStatus(int CivilStatusID, string CivilStatusName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_CivilStatus", ReplyAction="http://tempuri.org/itWebService/Save_CivilStatusResponse")]
        System.Threading.Tasks.Task Save_CivilStatusAsync(int CivilStatusID, string CivilStatusName, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_SystemModules", ReplyAction="http://tempuri.org/itWebService/Save_SystemModulesResponse")]
        void Save_SystemModules(int ModuleID, string ModuleName, string ModuleDescription, string ModuleURL, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_SystemModules", ReplyAction="http://tempuri.org/itWebService/Save_SystemModulesResponse")]
        System.Threading.Tasks.Task Save_SystemModulesAsync(int ModuleID, string ModuleName, string ModuleDescription, string ModuleURL, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Office", ReplyAction="http://tempuri.org/itWebService/Save_OfficeResponse")]
        void Save_Office(int OfficeID, string OfficeCode, string OfficeName, string OfficeAddress, string ContactNo, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Office", ReplyAction="http://tempuri.org/itWebService/Save_OfficeResponse")]
        System.Threading.Tasks.Task Save_OfficeAsync(int OfficeID, string OfficeCode, string OfficeName, string OfficeAddress, string ContactNo, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Department", ReplyAction="http://tempuri.org/itWebService/Save_DepartmentResponse")]
        void Save_Department(int DepartmentID, string DepartmentCode, string DepartmentName, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_Department", ReplyAction="http://tempuri.org/itWebService/Save_DepartmentResponse")]
        System.Threading.Tasks.Task Save_DepartmentAsync(int DepartmentID, string DepartmentCode, string DepartmentName, bool Active, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Validate_Token", ReplyAction="http://tempuri.org/itWebService/Validate_TokenResponse")]
        bool Validate_Token(int UserID, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Validate_Token", ReplyAction="http://tempuri.org/itWebService/Validate_TokenResponse")]
        System.Threading.Tasks.Task<bool> Validate_TokenAsync(int UserID, string TokenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TransactionHistory", ReplyAction="http://tempuri.org/itWebService/Get_TransactionHistoryResponse")]
        string Get_TransactionHistory(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Get_TransactionHistory", ReplyAction="http://tempuri.org/itWebService/Get_TransactionHistoryResponse")]
        System.Threading.Tasks.Task<string> Get_TransactionHistoryAsync(string _Parameter, int _UserID, string _Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TransactionHistory", ReplyAction="http://tempuri.org/itWebService/Save_TransactionHistoryResponse")]
        void Save_TransactionHistory(int UserID, string FormName, string EventName, string ExceptionError, string TransactionLogs, string ComputerName, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/itWebService/Save_TransactionHistory", ReplyAction="http://tempuri.org/itWebService/Save_TransactionHistoryResponse")]
        System.Threading.Tasks.Task Save_TransactionHistoryAsync(int UserID, string FormName, string EventName, string ExceptionError, string TransactionLogs, string ComputerName, string IPAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface itWebServiceChannel : webApplication_Tonsberg.wcfService.itWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class itWebServiceClient : System.ServiceModel.ClientBase<webApplication_Tonsberg.wcfService.itWebService>, webApplication_Tonsberg.wcfService.itWebService {
        
        public itWebServiceClient() {
        }
        
        public itWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public itWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public itWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public itWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get_TraineeProfile(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TraineeProfile(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TraineeProfileAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TraineeProfileAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_TraineeList(int _UserID, string _Token) {
            return base.Channel.Get_TraineeList(_UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TraineeListAsync(int _UserID, string _Token) {
            return base.Channel.Get_TraineeListAsync(_UserID, _Token);
        }
        
        public string Get_TraineeRecord(string TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TraineeRecord(TraineeID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TraineeRecordAsync(string TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TraineeRecordAsync(TraineeID, _UserID, _Token);
        }
        
        public string Get_AvailableCourses(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_AvailableCourses(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_AvailableCoursesAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_AvailableCoursesAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_EnrolledTrainee(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_EnrolledTrainee(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_EnrolledTraineeAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_EnrolledTraineeAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_TrainingCourses(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TrainingCourses(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TrainingCoursesAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TrainingCoursesAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_AccountsReceivableHistory(int _CourseID, string _TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_AccountsReceivableHistory(_CourseID, _TraineeID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_AccountsReceivableHistoryAsync(int _CourseID, string _TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_AccountsReceivableHistoryAsync(_CourseID, _TraineeID, _UserID, _Token);
        }
        
        public string Get_TotalAmountPaid(int _CourseID, string _TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TotalAmountPaid(_CourseID, _TraineeID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TotalAmountPaidAsync(int _CourseID, string _TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TotalAmountPaidAsync(_CourseID, _TraineeID, _UserID, _Token);
        }
        
        public string Get_TraineeAccountsReceivable(string TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TraineeAccountsReceivable(TraineeID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TraineeAccountsReceivableAsync(string TraineeID, int _UserID, string _Token) {
            return base.Channel.Get_TraineeAccountsReceivableAsync(TraineeID, _UserID, _Token);
        }
        
        public string GetUserPass(string Username, string Password) {
            return base.Channel.GetUserPass(Username, Password);
        }
        
        public System.Threading.Tasks.Task<string> GetUserPassAsync(string Username, string Password) {
            return base.Channel.GetUserPassAsync(Username, Password);
        }
        
        public string Get_UserAccessRights(int GroupID) {
            return base.Channel.Get_UserAccessRights(GroupID);
        }
        
        public System.Threading.Tasks.Task<string> Get_UserAccessRightsAsync(int GroupID) {
            return base.Channel.Get_UserAccessRightsAsync(GroupID);
        }
        
        public string Get_UserAccount(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_UserAccount(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_UserAccountAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_UserAccountAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_UserGroups(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_UserGroups(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_UserGroupsAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_UserGroupsAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_GroupRights(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_GroupRights(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_GroupRightsAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_GroupRightsAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_Gender(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_Gender(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_GenderAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_GenderAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_CivilStatus(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_CivilStatus(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_CivilStatusAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_CivilStatusAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_SystemModules(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_SystemModules(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_SystemModulesAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_SystemModulesAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_Office(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_Office(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_OfficeAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_OfficeAsync(_Parameter, _UserID, _Token);
        }
        
        public string Get_Department(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_Department(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_DepartmentAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_DepartmentAsync(_Parameter, _UserID, _Token);
        }
        
        public string Report_AccountsReceivable_All(string _DateFrom, string _DateTo, int _UserID, string _Token) {
            return base.Channel.Report_AccountsReceivable_All(_DateFrom, _DateTo, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Report_AccountsReceivable_AllAsync(string _DateFrom, string _DateTo, int _UserID, string _Token) {
            return base.Channel.Report_AccountsReceivable_AllAsync(_DateFrom, _DateTo, _UserID, _Token);
        }
        
        public string Report_AccountsReceivable_Course(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token) {
            return base.Channel.Report_AccountsReceivable_Course(_DateFrom, _DateTo, _CourseID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Report_AccountsReceivable_CourseAsync(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token) {
            return base.Channel.Report_AccountsReceivable_CourseAsync(_DateFrom, _DateTo, _CourseID, _UserID, _Token);
        }
        
        public string Report_Sales_All(string _DateFrom, string _DateTo, int _UserID, string _Token) {
            return base.Channel.Report_Sales_All(_DateFrom, _DateTo, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Report_Sales_AllAsync(string _DateFrom, string _DateTo, int _UserID, string _Token) {
            return base.Channel.Report_Sales_AllAsync(_DateFrom, _DateTo, _UserID, _Token);
        }
        
        public string Report_Sales_Course(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token) {
            return base.Channel.Report_Sales_Course(_DateFrom, _DateTo, _CourseID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Report_Sales_CourseAsync(string _DateFrom, string _DateTo, int _CourseID, int _UserID, string _Token) {
            return base.Channel.Report_Sales_CourseAsync(_DateFrom, _DateTo, _CourseID, _UserID, _Token);
        }
        
        public void Save_TraineeProfile(
                    string TraineeID, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    int GenderID, 
                    int CivilStatusID, 
                    string ContactNo, 
                    string DateOfBirth, 
                    int Age, 
                    string PlaceOfBirth, 
                    bool Active, 
                    string PositionRank, 
                    int YearsOfSeaExperience, 
                    string MarinaLicense, 
                    string PRCLicense, 
                    string SIRBNo, 
                    string PassportNo, 
                    string SRCNo, 
                    string Others, 
                    string EnrollmentDate, 
                    int _UserID, 
                    string _Token) {
            base.Channel.Save_TraineeProfile(TraineeID, FirstName, MiddleName, LastName, GenderID, CivilStatusID, ContactNo, DateOfBirth, Age, PlaceOfBirth, Active, PositionRank, YearsOfSeaExperience, MarinaLicense, PRCLicense, SIRBNo, PassportNo, SRCNo, Others, EnrollmentDate, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_TraineeProfileAsync(
                    string TraineeID, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    int GenderID, 
                    int CivilStatusID, 
                    string ContactNo, 
                    string DateOfBirth, 
                    int Age, 
                    string PlaceOfBirth, 
                    bool Active, 
                    string PositionRank, 
                    int YearsOfSeaExperience, 
                    string MarinaLicense, 
                    string PRCLicense, 
                    string SIRBNo, 
                    string PassportNo, 
                    string SRCNo, 
                    string Others, 
                    string EnrollmentDate, 
                    int _UserID, 
                    string _Token) {
            return base.Channel.Save_TraineeProfileAsync(TraineeID, FirstName, MiddleName, LastName, GenderID, CivilStatusID, ContactNo, DateOfBirth, Age, PlaceOfBirth, Active, PositionRank, YearsOfSeaExperience, MarinaLicense, PRCLicense, SIRBNo, PassportNo, SRCNo, Others, EnrollmentDate, _UserID, _Token);
        }
        
        public void Save_TraineeRegistration(int RegistrationID, string DateRegistered, string TraineeID, int CourseID, string CourseCode, bool DropTrainee, int _UserID, string _Token) {
            base.Channel.Save_TraineeRegistration(RegistrationID, DateRegistered, TraineeID, CourseID, CourseCode, DropTrainee, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_TraineeRegistrationAsync(int RegistrationID, string DateRegistered, string TraineeID, int CourseID, string CourseCode, bool DropTrainee, int _UserID, string _Token) {
            return base.Channel.Save_TraineeRegistrationAsync(RegistrationID, DateRegistered, TraineeID, CourseID, CourseCode, DropTrainee, _UserID, _Token);
        }
        
        public void Save_DropTrainee(string TraineeID, int CourseID, int RegistrationID, int _UserID, string _Token) {
            base.Channel.Save_DropTrainee(TraineeID, CourseID, RegistrationID, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_DropTraineeAsync(string TraineeID, int CourseID, int RegistrationID, int _UserID, string _Token) {
            return base.Channel.Save_DropTraineeAsync(TraineeID, CourseID, RegistrationID, _UserID, _Token);
        }
        
        public void Save_TrainingCourses(int CourseID, string CourseCode, string CourseName, string TrainorName, int NoOfTrainees, int TrainingDuration, string TrainingStartDate, bool Active, decimal TrainingFee, string AssessorName, int _UserID, string _Token) {
            base.Channel.Save_TrainingCourses(CourseID, CourseCode, CourseName, TrainorName, NoOfTrainees, TrainingDuration, TrainingStartDate, Active, TrainingFee, AssessorName, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_TrainingCoursesAsync(int CourseID, string CourseCode, string CourseName, string TrainorName, int NoOfTrainees, int TrainingDuration, string TrainingStartDate, bool Active, decimal TrainingFee, string AssessorName, int _UserID, string _Token) {
            return base.Channel.Save_TrainingCoursesAsync(CourseID, CourseCode, CourseName, TrainorName, NoOfTrainees, TrainingDuration, TrainingStartDate, Active, TrainingFee, AssessorName, _UserID, _Token);
        }
        
        public void Save_Payments(int RegistrationID, decimal AmountPaid, string PaymentDetails, int _UserID, string _Token) {
            base.Channel.Save_Payments(RegistrationID, AmountPaid, PaymentDetails, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_PaymentsAsync(int RegistrationID, decimal AmountPaid, string PaymentDetails, int _UserID, string _Token) {
            return base.Channel.Save_PaymentsAsync(RegistrationID, AmountPaid, PaymentDetails, _UserID, _Token);
        }
        
        public void Save_UserAccounts(int UserID, string UserName, string Password, string FirstName, string LastName, int GroupID, string EmailAddress, string Office, int DepartmentID, bool Active, int _UserID, string _Token) {
            base.Channel.Save_UserAccounts(UserID, UserName, Password, FirstName, LastName, GroupID, EmailAddress, Office, DepartmentID, Active, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_UserAccountsAsync(int UserID, string UserName, string Password, string FirstName, string LastName, int GroupID, string EmailAddress, string Office, int DepartmentID, bool Active, int _UserID, string _Token) {
            return base.Channel.Save_UserAccountsAsync(UserID, UserName, Password, FirstName, LastName, GroupID, EmailAddress, Office, DepartmentID, Active, _UserID, _Token);
        }
        
        public void Save_UserGroups(int ID, string GroupName, string Description, bool Active, int _UserID, string _Token) {
            base.Channel.Save_UserGroups(ID, GroupName, Description, Active, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_UserGroupsAsync(int ID, string GroupName, string Description, bool Active, int _UserID, string _Token) {
            return base.Channel.Save_UserGroupsAsync(ID, GroupName, Description, Active, _UserID, _Token);
        }
        
        public void Save_GroupRights(int GroupRightID, int GroupID, int ModuleID, bool CanView, bool CanEdit, bool CanDelete, int _UserID, string _Token) {
            base.Channel.Save_GroupRights(GroupRightID, GroupID, ModuleID, CanView, CanEdit, CanDelete, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_GroupRightsAsync(int GroupRightID, int GroupID, int ModuleID, bool CanView, bool CanEdit, bool CanDelete, int _UserID, string _Token) {
            return base.Channel.Save_GroupRightsAsync(GroupRightID, GroupID, ModuleID, CanView, CanEdit, CanDelete, _UserID, _Token);
        }
        
        public void Save_UserProfile(int UserID, string Password, int _UserID, string _Token) {
            base.Channel.Save_UserProfile(UserID, Password, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_UserProfileAsync(int UserID, string Password, int _UserID, string _Token) {
            return base.Channel.Save_UserProfileAsync(UserID, Password, _UserID, _Token);
        }
        
        public void Save_Gender(int GenderID, string GenderName, int _UserID, string _Token) {
            base.Channel.Save_Gender(GenderID, GenderName, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_GenderAsync(int GenderID, string GenderName, int _UserID, string _Token) {
            return base.Channel.Save_GenderAsync(GenderID, GenderName, _UserID, _Token);
        }
        
        public void Save_CivilStatus(int CivilStatusID, string CivilStatusName, int _UserID, string _Token) {
            base.Channel.Save_CivilStatus(CivilStatusID, CivilStatusName, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_CivilStatusAsync(int CivilStatusID, string CivilStatusName, int _UserID, string _Token) {
            return base.Channel.Save_CivilStatusAsync(CivilStatusID, CivilStatusName, _UserID, _Token);
        }
        
        public void Save_SystemModules(int ModuleID, string ModuleName, string ModuleDescription, string ModuleURL, int _UserID, string _Token) {
            base.Channel.Save_SystemModules(ModuleID, ModuleName, ModuleDescription, ModuleURL, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_SystemModulesAsync(int ModuleID, string ModuleName, string ModuleDescription, string ModuleURL, int _UserID, string _Token) {
            return base.Channel.Save_SystemModulesAsync(ModuleID, ModuleName, ModuleDescription, ModuleURL, _UserID, _Token);
        }
        
        public void Save_Office(int OfficeID, string OfficeCode, string OfficeName, string OfficeAddress, string ContactNo, bool Active, int _UserID, string _Token) {
            base.Channel.Save_Office(OfficeID, OfficeCode, OfficeName, OfficeAddress, ContactNo, Active, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_OfficeAsync(int OfficeID, string OfficeCode, string OfficeName, string OfficeAddress, string ContactNo, bool Active, int _UserID, string _Token) {
            return base.Channel.Save_OfficeAsync(OfficeID, OfficeCode, OfficeName, OfficeAddress, ContactNo, Active, _UserID, _Token);
        }
        
        public void Save_Department(int DepartmentID, string DepartmentCode, string DepartmentName, bool Active, int _UserID, string _Token) {
            base.Channel.Save_Department(DepartmentID, DepartmentCode, DepartmentName, Active, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task Save_DepartmentAsync(int DepartmentID, string DepartmentCode, string DepartmentName, bool Active, int _UserID, string _Token) {
            return base.Channel.Save_DepartmentAsync(DepartmentID, DepartmentCode, DepartmentName, Active, _UserID, _Token);
        }
        
        public bool Validate_Token(int UserID, string TokenID) {
            return base.Channel.Validate_Token(UserID, TokenID);
        }
        
        public System.Threading.Tasks.Task<bool> Validate_TokenAsync(int UserID, string TokenID) {
            return base.Channel.Validate_TokenAsync(UserID, TokenID);
        }
        
        public string Get_TransactionHistory(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TransactionHistory(_Parameter, _UserID, _Token);
        }
        
        public System.Threading.Tasks.Task<string> Get_TransactionHistoryAsync(string _Parameter, int _UserID, string _Token) {
            return base.Channel.Get_TransactionHistoryAsync(_Parameter, _UserID, _Token);
        }
        
        public void Save_TransactionHistory(int UserID, string FormName, string EventName, string ExceptionError, string TransactionLogs, string ComputerName, string IPAddress) {
            base.Channel.Save_TransactionHistory(UserID, FormName, EventName, ExceptionError, TransactionLogs, ComputerName, IPAddress);
        }
        
        public System.Threading.Tasks.Task Save_TransactionHistoryAsync(int UserID, string FormName, string EventName, string ExceptionError, string TransactionLogs, string ComputerName, string IPAddress) {
            return base.Channel.Save_TransactionHistoryAsync(UserID, FormName, EventName, ExceptionError, TransactionLogs, ComputerName, IPAddress);
        }
    }
}
